name: siphash
version: '0.0.5'
summary: An implementation of SipHash 1-3, 2-4, et al. in pure Ruby.
description: |
  A slow, Ruby implementation of SipHash that includes a `siphash` command line
  utility. "SipHash is a family of pseudorandom functions (a.k.a. keyed hash
  functions) optimized for speed on short messages."
grade: stable
confinement: strict

apps:
  siphash:
    command: bin/siphash

parts:
  siphash:
    source: .
    plugin: ruby
    gems: [digest-sip_hash]
    ruby-version: '2.5.3'
