---
name: CI
'on': [push, pull_request]

jobs:
  rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: ['3.3', '3.4']

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ext/digest_sip_hash_native/target/
          key: >-
            ${{ runner.os }}-ruby-${{ matrix.ruby }}-${{
            hashFiles('**/Cargo.lock') }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake test_native
      - run: >-
          ruby -I lib -r digest/sip_hash -e
          'abort unless Digest::SipHash.native?'

  ruby:
    runs-on: ubuntu-latest
    env:
      DIGEST_SIPHASH_DISABLE_NATIVE: '1'
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - run: bundle exec rake test
      - run: >-
          ruby -I lib -r digest/sip_hash -e
          'abort if Digest::SipHash.native?'
